/// Generated by AssetsRefGenerator on 2020/08/09
class Res {
  static const String Cairo = "assets/fonts/Cairo.ttf";
  static const String caricon = "assets/icons/caricon.png";
  static const String computer = "assets/icons/computer.png";
  static const String cow = "assets/icons/cow.png";
  static const String creditcard = "assets/icons/creditcard.png";
  static const String home = "assets/icons/home.png";
  static const String logo = "assets/icons/logo.png";
  static const String man = "assets/icons/man.png";
  static const String messages = "assets/icons/messages.png";
  static const String money = "assets/icons/money.png";
  static const String person = "assets/icons/person.png";
  static const String phone = "assets/icons/phone.png";
  static const String report = "assets/icons/report.png";
  static const String sofa = "assets/icons/sofa.png";
  static const String stop = "assets/icons/stop.png";
  static const String unknown = "assets/icons/unknown.png";
  static const String wallpaper = "assets/icons/wallpaper.png";
  static const String warning = "assets/icons/warning.png";
  static const String backsplash = "assets/images/backsplash.png";
}
